# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/houwang/projects/FileStorage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/houwang/projects/FileStorage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/houwang/projects/FileStorage/CMakeFiles /Users/houwang/projects/FileStorage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/houwang/projects/FileStorage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfarchiver

# Build rule for target.
sfarchiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfarchiver
.PHONY : sfarchiver

# fast build rule for target.
sfarchiver/fast:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/build
.PHONY : sfarchiver/fast

#=============================================================================
# Target rules for targets named CommandProcessor

# Build rule for target.
CommandProcessor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CommandProcessor
.PHONY : CommandProcessor

# fast build rule for target.
CommandProcessor/fast:
	$(MAKE) -f CMakeFiles/CommandProcessor.dir/build.make CMakeFiles/CommandProcessor.dir/build
.PHONY : CommandProcessor/fast

#=============================================================================
# Target rules for targets named FileStorageEngine

# Build rule for target.
FileStorageEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileStorageEngine
.PHONY : FileStorageEngine

# fast build rule for target.
FileStorageEngine/fast:
	$(MAKE) -f CMakeFiles/FileStorageEngine.dir/build.make CMakeFiles/FileStorageEngine.dir/build
.PHONY : FileStorageEngine/fast

CommandProcessor.o: CommandProcessor.cpp.o

.PHONY : CommandProcessor.o

# target to build an object file
CommandProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/CommandProcessor.dir/build.make CMakeFiles/CommandProcessor.dir/CommandProcessor.cpp.o
.PHONY : CommandProcessor.cpp.o

CommandProcessor.i: CommandProcessor.cpp.i

.PHONY : CommandProcessor.i

# target to preprocess a source file
CommandProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/CommandProcessor.dir/build.make CMakeFiles/CommandProcessor.dir/CommandProcessor.cpp.i
.PHONY : CommandProcessor.cpp.i

CommandProcessor.s: CommandProcessor.cpp.s

.PHONY : CommandProcessor.s

# target to generate assembly for a file
CommandProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/CommandProcessor.dir/build.make CMakeFiles/CommandProcessor.dir/CommandProcessor.cpp.s
.PHONY : CommandProcessor.cpp.s

FileStorageEngine.o: FileStorageEngine.cpp.o

.PHONY : FileStorageEngine.o

# target to build an object file
FileStorageEngine.cpp.o:
	$(MAKE) -f CMakeFiles/FileStorageEngine.dir/build.make CMakeFiles/FileStorageEngine.dir/FileStorageEngine.cpp.o
.PHONY : FileStorageEngine.cpp.o

FileStorageEngine.i: FileStorageEngine.cpp.i

.PHONY : FileStorageEngine.i

# target to preprocess a source file
FileStorageEngine.cpp.i:
	$(MAKE) -f CMakeFiles/FileStorageEngine.dir/build.make CMakeFiles/FileStorageEngine.dir/FileStorageEngine.cpp.i
.PHONY : FileStorageEngine.cpp.i

FileStorageEngine.s: FileStorageEngine.cpp.s

.PHONY : FileStorageEngine.s

# target to generate assembly for a file
FileStorageEngine.cpp.s:
	$(MAKE) -f CMakeFiles/FileStorageEngine.dir/build.make CMakeFiles/FileStorageEngine.dir/FileStorageEngine.cpp.s
.PHONY : FileStorageEngine.cpp.s

fsClient.o: fsClient.cpp.o

.PHONY : fsClient.o

# target to build an object file
fsClient.cpp.o:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/fsClient.cpp.o
.PHONY : fsClient.cpp.o

fsClient.i: fsClient.cpp.i

.PHONY : fsClient.i

# target to preprocess a source file
fsClient.cpp.i:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/fsClient.cpp.i
.PHONY : fsClient.cpp.i

fsClient.s: fsClient.cpp.s

.PHONY : fsClient.s

# target to generate assembly for a file
fsClient.cpp.s:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/fsClient.cpp.s
.PHONY : fsClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sfarchiver"
	@echo "... CommandProcessor"
	@echo "... FileStorageEngine"
	@echo "... CommandProcessor.o"
	@echo "... CommandProcessor.i"
	@echo "... CommandProcessor.s"
	@echo "... FileStorageEngine.o"
	@echo "... FileStorageEngine.i"
	@echo "... FileStorageEngine.s"
	@echo "... fsClient.o"
	@echo "... fsClient.i"
	@echo "... fsClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

