# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/houwang/projects/FileStorage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/houwang/projects/FileStorage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/houwang/projects/FileStorage/CMakeFiles /Users/houwang/projects/FileStorage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/houwang/projects/FileStorage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named commandParser.hpp

# Build rule for target.
commandParser.hpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commandParser.hpp
.PHONY : commandParser.hpp

# fast build rule for target.
commandParser.hpp/fast:
	$(MAKE) -f CMakeFiles/commandParser.hpp.dir/build.make CMakeFiles/commandParser.hpp.dir/build
.PHONY : commandParser.hpp/fast

#=============================================================================
# Target rules for targets named sfarchiver

# Build rule for target.
sfarchiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfarchiver
.PHONY : sfarchiver

# fast build rule for target.
sfarchiver/fast:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/build
.PHONY : sfarchiver/fast

#=============================================================================
# Target rules for targets named FileStorageEngine.hpp

# Build rule for target.
FileStorageEngine.hpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileStorageEngine.hpp
.PHONY : FileStorageEngine.hpp

# fast build rule for target.
FileStorageEngine.hpp/fast:
	$(MAKE) -f CMakeFiles/FileStorageEngine.hpp.dir/build.make CMakeFiles/FileStorageEngine.hpp.dir/build
.PHONY : FileStorageEngine.hpp/fast

#=============================================================================
# Target rules for targets named Argument.hpp

# Build rule for target.
Argument.hpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Argument.hpp
.PHONY : Argument.hpp

# fast build rule for target.
Argument.hpp/fast:
	$(MAKE) -f CMakeFiles/Argument.hpp.dir/build.make CMakeFiles/Argument.hpp.dir/build
.PHONY : Argument.hpp/fast

Argument.o: Argument.cpp.o

.PHONY : Argument.o

# target to build an object file
Argument.cpp.o:
	$(MAKE) -f CMakeFiles/Argument.hpp.dir/build.make CMakeFiles/Argument.hpp.dir/Argument.cpp.o
.PHONY : Argument.cpp.o

Argument.i: Argument.cpp.i

.PHONY : Argument.i

# target to preprocess a source file
Argument.cpp.i:
	$(MAKE) -f CMakeFiles/Argument.hpp.dir/build.make CMakeFiles/Argument.hpp.dir/Argument.cpp.i
.PHONY : Argument.cpp.i

Argument.s: Argument.cpp.s

.PHONY : Argument.s

# target to generate assembly for a file
Argument.cpp.s:
	$(MAKE) -f CMakeFiles/Argument.hpp.dir/build.make CMakeFiles/Argument.hpp.dir/Argument.cpp.s
.PHONY : Argument.cpp.s

FileStorageEngine.o: FileStorageEngine.cpp.o

.PHONY : FileStorageEngine.o

# target to build an object file
FileStorageEngine.cpp.o:
	$(MAKE) -f CMakeFiles/FileStorageEngine.hpp.dir/build.make CMakeFiles/FileStorageEngine.hpp.dir/FileStorageEngine.cpp.o
.PHONY : FileStorageEngine.cpp.o

FileStorageEngine.i: FileStorageEngine.cpp.i

.PHONY : FileStorageEngine.i

# target to preprocess a source file
FileStorageEngine.cpp.i:
	$(MAKE) -f CMakeFiles/FileStorageEngine.hpp.dir/build.make CMakeFiles/FileStorageEngine.hpp.dir/FileStorageEngine.cpp.i
.PHONY : FileStorageEngine.cpp.i

FileStorageEngine.s: FileStorageEngine.cpp.s

.PHONY : FileStorageEngine.s

# target to generate assembly for a file
FileStorageEngine.cpp.s:
	$(MAKE) -f CMakeFiles/FileStorageEngine.hpp.dir/build.make CMakeFiles/FileStorageEngine.hpp.dir/FileStorageEngine.cpp.s
.PHONY : FileStorageEngine.cpp.s

commandParser.o: commandParser.cpp.o

.PHONY : commandParser.o

# target to build an object file
commandParser.cpp.o:
	$(MAKE) -f CMakeFiles/commandParser.hpp.dir/build.make CMakeFiles/commandParser.hpp.dir/commandParser.cpp.o
.PHONY : commandParser.cpp.o

commandParser.i: commandParser.cpp.i

.PHONY : commandParser.i

# target to preprocess a source file
commandParser.cpp.i:
	$(MAKE) -f CMakeFiles/commandParser.hpp.dir/build.make CMakeFiles/commandParser.hpp.dir/commandParser.cpp.i
.PHONY : commandParser.cpp.i

commandParser.s: commandParser.cpp.s

.PHONY : commandParser.s

# target to generate assembly for a file
commandParser.cpp.s:
	$(MAKE) -f CMakeFiles/commandParser.hpp.dir/build.make CMakeFiles/commandParser.hpp.dir/commandParser.cpp.s
.PHONY : commandParser.cpp.s

fsClient.o: fsClient.cpp.o

.PHONY : fsClient.o

# target to build an object file
fsClient.cpp.o:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/fsClient.cpp.o
.PHONY : fsClient.cpp.o

fsClient.i: fsClient.cpp.i

.PHONY : fsClient.i

# target to preprocess a source file
fsClient.cpp.i:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/fsClient.cpp.i
.PHONY : fsClient.cpp.i

fsClient.s: fsClient.cpp.s

.PHONY : fsClient.s

# target to generate assembly for a file
fsClient.cpp.s:
	$(MAKE) -f CMakeFiles/sfarchiver.dir/build.make CMakeFiles/sfarchiver.dir/fsClient.cpp.s
.PHONY : fsClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... commandParser.hpp"
	@echo "... sfarchiver"
	@echo "... FileStorageEngine.hpp"
	@echo "... edit_cache"
	@echo "... Argument.hpp"
	@echo "... Argument.o"
	@echo "... Argument.i"
	@echo "... Argument.s"
	@echo "... FileStorageEngine.o"
	@echo "... FileStorageEngine.i"
	@echo "... FileStorageEngine.s"
	@echo "... commandParser.o"
	@echo "... commandParser.i"
	@echo "... commandParser.s"
	@echo "... fsClient.o"
	@echo "... fsClient.i"
	@echo "... fsClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

